FROM python:latest-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

FROM python:3.13.4-slim-bullseye
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY ./app ./app
COPY .env .env
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--workers","4"]
