name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
            python-version: '3.13'
      - name: Install backend deps
        run: |
          cd backend
          python -m venv .venv
          .venv/bin/activate
          pip install -r requirements.txt
      - name: Lint and Test
        run: |
          cd backend
          .venv/bin/activate
          flake8 app
          pytest --maxfail=1 --disable-warnings -q --cov=app

      - name: Build and Cache Frontend
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: |
          cd frontend
          pnpm install
          pnpm run build
          
      # เพิ่มขั้นตอนสำหรับ Frontend Unit Tests
      - name: Run Frontend Unit Tests
        run: |
          cd frontend
          npm install
          npm run test -- --coverage

      # เพิ่มขั้นตอนสำหรับ Cypress Tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          browser: chrome
